# paasta-pinpoint-vsphere 설정 파일 내용
name: "((deployment_name))"         	# 서비스 배포이름(필수)

update:
  canaries: 1                       	# canary 인스턴스 수(필수)
  canary_watch_time: 120000         	# canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 120000		# non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 8         		# non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)

stemcells:
- alias: "((stemcell_alias))"
  os: "((stemcell_os))"
  version: "((stemcell_version))"

releases:
- name: paasta-pinpoint-monitoring-release
  url: http://45.248.73.44/index.php/s/mSTCyEM3mN4g2Jo/download
  version: 1.1
  sha1: c4472ffa463fe8af6a5b805a7268bcdbec030310

instance_groups:
- name: h_master                    	#작업 이름(필수)
  azs: ((h_master_azs))
  instances: ((h_master_instances)) 	# job 인스턴스 수(필수)
  vm_type: "((h_master_vm_type))"
  stemcell: "((stemcell_alias))"
  persistent_disk_type: "((h_master_persistent_disk_type))"
  networks:                         	# 네트워크 구성정보          
  - name: "((h_master_network))"    	# Networks block에서 선언한 network 이름(필수)
  jobs:
  - name: h_master
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    pem_key: ((pem_key))
    PemSSH: ((PemSSH))

- name: collector                  	#작업 이름(필수)
  azs: ((collector_azs))
  instances: ((collector_instances))	# job 인스턴스 수(필수)
  vm_type: "((collector_vm_type))"
  stemcell: "((stemcell_alias))"
  persistent_disk_type: "((collector_persistent_disk_type))"
  networks:                           	# 네트워크 구성정보          
  - name: "((collector_network))"     	# Networks block에서 선언한 network 이름(필수)
  jobs:
  - name: collector 
    release: "((releases_name))"
  syslog_aggregator: null

- name: pinpoint_web                          	#작업 이름(필수)
  azs: ((pinpoint_web_azs))
  instances: ((collector_instances))           	# job 인스턴스 수(필수)
  vm_type: "((collector_vm_type))"
  stemcell: "((stemcell_alias))"
  persistent_disk_type: "((collector_persistent_disk_type))"
  networks:                               	# 네트워크 구성정보          
  - name: "((collector_network))"              	# Networks block에서 선언한 network 이름(필수)
  jobs:
  - name: pinpoint_web
    release: "((releases_name))"
  syslog_aggregator: null

- name: haproxy_webui                         	#작업 이름(필수)
  azs: ((haproxy_webui_azs))
  instances: ((pinpoint_web_instances))       	# job 인스턴스 수(필수)
  vm_type: "((pinpoint_web_vm_type))"
  stemcell: "((stemcell_alias))"
  persistent_disk_type: "((haproxy_webui_persistent_disk_type))"
  networks:                             	# 네트워크 구성정보          
  - name: "((haproxy_webui_network))"   	# Networks block에서 선언한 network 이름(필수)
  - name: "((public_networks_name))"
    static_ips: "((saas_monitoring_url))"
  jobs:
  - name: haproxy_webui
    release: "((releases_name))"
  syslog_aggregator: null

properties:                                # Pinpoint 설정정보
  master:                                  # Pinpoint master 설정정보
    replication: 1                         # Pinpoint master 복제개수
    tcp_listen_port: 29994                 # Pinpoint master tcp port
  yarn:                                    # Pinpoint yarn 설정정보      
    resource_tracker_port: 8025            # Pinpoint yarn resource_tracker_port
    scheduler_port: 8030                   # Pinpoint yarn scheduler_port
    resourcemanager_port: 8040             # Pinpoint yarn resourcemanager_port
