---
name: paasta-monitoring

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))

releases:
- name: paasta-monitoring-release
  sha1: 458773bc0973336447cf227828f17cce57906d14 
  version: "5.0"
  url: http://45.248.73.44/index.php/s/42RtMHzoNmpWbSZ/download
- name: bpm
  sha1: 44ffa71e70adfb262655253662c83148581ac970
  url: http://45.248.73.44/index.php/s/bMDXYCEQ85dMt6o/download
  version: '1.1.0'
- name: redis
  version: '14.0.1'
  url: http://45.248.73.44/index.php/s/FMwXoWTPK9YtSCJ/download
  sha1: fd4a6107e1fb8aca1d551054d8bc07e4f53ddf05
- name: influxdb
  version: '1.5.1'
  url: http://45.248.73.44/index.php/s/LDwdpizbw8fecZQ/download
  sha1: 2337d1f26f46100b8d438b50b71e300941da74a2


instance_groups:
- name: redis
  azs: ((redis_azs))
  instances: ((redis_instances))
  vm_type: ((redis_vm_type))
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: ((redis_network))
    static_ips:
    - ((redis_ip))
 
  jobs:
  - name: redis
    release: redis
    properties:
      password: ((redis_password))
- name: sanity-tests
  azs: ((sanity_tests_azs))
  instances: ((sanity_tests_instances))
  lifecycle: errand
  vm_type: ((sanity_tests_vm_type))
  stemcell: default
  networks: [{name: ((sanity_tests_network))}]
  jobs:
  - name: sanity-tests
    release: redis

- name: influxdb
  azs: ((influxdb_azs))
  instances: ((influxdb_instances))
  vm_type: ((influxdb_vm_type))
  stemcell: default
  persistent_disk_type: ((influxdb_persistent_disk_type))
  networks:
  - name: ((influxdb_network))
    static_ips:
    - ((metric_url)) 

  jobs:
  - name: influxdb
    release: influxdb
    properties:
      influxdb:
        database: cf_metric_db
        user: root
        password: root
        replication: 1
        ips: 127.0.0.1
  - name: chronograf
    release: influxdb

- name: mariadb
  azs: ((mariadb_azs))
  instances: ((mariadb_instances))
  vm_type: ((mariadb_vm_type)) 
  stemcell: default
  persistent_disk_type: ((mariadb_persistent_disk_type))
  networks:
  - name: ((mariadb_network))
    static_ips: 
    - ((mariadb_ip))
  jobs:
  - name: mariadb
    release: paasta-monitoring-release
    properties:
      mariadb:
        port: ((mariadb_port))
        admin_user:
          password: '((mariadb_password))'

- name: monitoring-batch
  azs: ((monitoring_batch_azs))
  instances: ((monitoring_batch_instances))
  vm_type: ((monitoring_batch_vm_type)) 
  stemcell: default
  networks:
  - name: ((monitoring_batch_network))
  jobs:
  - name: monitoring-batch
    release: paasta-monitoring-release
    consumes:
      influxdb: {from: influxdb}
    properties:
      monitoring-batch:
        influxdb:
          url: ((metric_url)):8086
        db:
          ip: ((mariadb_ip))
          port: ((mariadb_port))
          username: ((mariadb_username))
          password: ((mariadb_password))
        paasta:
          cell_prefix: ((paasta_cell_prefix))
        bosh:
          url: ((bosh_url))
          password: ((bosh_client_admin_secret))
          director_name: ((director_name))
          paasta:
            deployments: ((paasta_deploy_name))
        mail:
          smtp:
            url: ((smtp_url))
            port: ((smtp_port))
          sender:
            name: ((mail_sender))
            password: ((mail_password))
          resource:
            url: ((resource_url))
          send: ((mail_enable))
          tls: ((mail_tls_enable))
        redis:
          url: ((redis_ip)):6379
          password: ((redis_password))
        paasta:
          apiurl: http://api.((system_domain))
          uaaurl: https://uaa.((system_domain))
          username: ((paasta_admin_username))
          password: ((paasta_admin_password))

- name: caas-monitoring-batch
  azs: ((caas_monitoring_batch_azs))
  instances: ((monitoring_batch_instances))
  vm_type: ((caas_monitoring_batch_vm_type))
  stemcell: default
  networks:
  - name: ((caas_monitoring_batch_network))
  jobs:
  - name: caas-monitoring-batch
    release: paasta-monitoring-release
    consumes:
      influxdb: {from: influxdb}
    properties:
      caas-monitoring-batch:
        db:
          ip: ((mariadb_ip))
          port: ((mariadb_port))
          username: ((mariadb_username))
          password: ((mariadb_password))
        mail:
          smtp:
            url: ((smtp_url))
            port: ((smtp_port))
          sender:
            name: ((mail_sender))
            password: ((mail_password))
          resource:
            url: ((resource_url))
          send: ((mail_enable))
          tls: ((mail_tls_enable))
        public:
          url: ((monitoring_api_url)):8080

- name: saas-monitoring-batch
  azs: ((saas_monitoring_batch_azs))
  instances: ((saas_monitoring_batch_instances))
  vm_type: ((saas_monitoring_batch_vm_type))
  stemcell: default
  networks:
  - name: ((saas_monitoring_batch_network))
  jobs:
  - name: saas-monitoring-batch
    release: paasta-monitoring-release
    consumes:
      influxdb: {from: influxdb}
    properties:
     saas-monitoring-batch:
        db:
          ip: ((mariadb_ip))
          port: ((mariadb_port))
          username: ((mariadb_username))
          password: ((mariadb_password))
        mail:
          smtp:
            url: ((smtp_url))
            port: ((smtp_port))
          sender:
            name: ((mail_sender))
            password: ((mail_password))
          resource:
            url: ((resource_url))
          send: ((mail_enable))
          tls: ((mail_tls_enable))
        pinpoint:
          url: ((saas_monitoring_url)):8079

- name: monitoring-web
  azs: ((monitoring_web_azs))
  instances: ((monitoring_web_instances))
  vm_type: ((monitoring_web_vm_type)) 
  stemcell: default
  networks:
  - name: ((monitoring_web_network))
    default: [dns, gateway]
  - name: ((public_network_name))
    static_ips: [((monitoring_api_url))]

  jobs:
  - name: monitoring-web
    release: paasta-monitoring-release
    properties:
      monitoring-web:
        db:
          ip: ((mariadb_ip))
          port: ((mariadb_port))
          username: ((mariadb_username))
          password: ((mariadb_password))
        influxdb:
          url: http://((metric_url)):8086
        paasta:
          system_domain: ((system_domain))
        bosh:
          ip: ((bosh_url))
          password: ((bosh_client_admin_secret))
          director_name: ((director_name))
        redis:
          url: ((redis_ip)):6379
          password: ((redis_password))
        time:
          gap: ((utc_time_gap))
        prometheus:
          url: ((prometheus_ip)):30090
        kubernetes:
          url: ((kubernetes_ip)):8443
          token: ((kubernetes_token))
        pinpoint:
          url: ((saas_monitoring_url)):8079
        pinpointWas:
          url: ((pinpoint_was_ip)):8080
        caasbroker:
          url: ((cassbroker_ip)):3334
        system:
          type: ((system_type))

variables:
- name: redis_password
  type: password

update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-180000
